# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Base Patterns
tagline:          "A good designer must rely on experience, on precise, logic thinking; and on pedantic exactness. No magic will do." - Niklaus Wirth
url:              http://basepatterns.org
paginate:         1
baseurl:          /
author:
  name:           Ben Fortuna
  url:            https://twitter.com/elbento
  email:          fortuna@micronode.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/benfortuna/fortuna.github.io
